[package]
name = "cli-rs"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
node-bindgen = "6.0.1"
tslink = "0.1.0"

[build-dependencies]
node-bindgen = { version = "6.0.1", default-features = false, features = [
  "build",
] }
