[package]
name = "ahqstore_cli_rs"
version = "1.0.0-rc11"
edition = "2021"
description = "AHQ Store CLI"
repository = "https://github.com/ahqstore/cli"
homepage = "https://github.com/ahqstore/cli"
license = "MIT"
exclude = ["dist/**", "finalize.js", "tslink.toml"]

[lib]
name = "ahqstore_cli_rs"
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "ahqstore"
path = "src/main.rs"

[dependencies]
node-bindgen = "6.0.1"
tslink = "0.1.0"
inquire = "0.6.2"
chalk_rs = "1.0.1"
lazy_static = "1.4.0"

[build-dependencies]
node-bindgen = { version = "6.0.1", default-features = false, features = [
  "build",
] }
